### ISSUE TITLE
Compat issue with Fabric builds

### ISSUE THREAD

**Issue by Sunconure11** [Tsukimi-Ren/Casualness-Delight#3]
https://gist.github.com/Sunconure11/3037cfa4fc0808293ca904c8df634ce8

**Comment by Sunconure11** [comment]
The issue seems to be related to usage of Quilt.

@Tsukimi-Ren

**Comment by Tsukimi-Ren** [comment]
ummm,This was caused by an oversight during the previous upload,Now fixed，Please download again on modrinth

**Comment by Sunconure11** [comment]
Has the build even been approved? I don’t see any… difference.

**Comment by Tsukimi-Ren** [comment]
Because the content has not changed，So I just replaced the fabric version of the file and didn't create a new version
