### ISSUE TITLE
Yorkshire Pudding has no crafting recipe

### ISSUE THREAD

**Issue by ryleu** [Tsukimi-Ren/Casualness-Delight#6]
Title. I'm using the 1.19.2 version of the mod.

**Comment by linaraincalzando** [comment]
I am 1.20.1 and Yorkshire Pudding is also not showing up with a recipe on this version too.

**Comment by KawaiShio** [comment]
Because I haven't figured out what to do with it yet

**Comment by ryleu** [comment]
https://www.thespruceeats.com/history-of-the-yorkshire-pudding-435209

hmm yeah, it's difficult to find anything substantial about it. maybe that fact in and of itself could be inspiration? maybe it could let the people who eat it turn invisible, avoid damage, or perhaps go through blocks?
