### ISSUE TITLE
Causes Server crash on startup

### ISSUE THREAD

**Issue by JasdanVM** [Tsukimi-Ren/Casualness-Delight#7]
It works great on singleplayer with a backup of the server, but not in the server itself.

I have a 1.20.1 Fabric server on Microsoft Azure

Latest version of the mod

[https://pastebin.com/KmPdNxWA](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252fKmPdNxWA)

 

The error according to the log seems to be  a java.lang.NoSuchMethodError

**Comment by naomieow** [comment]
Caused by the `@Environment(EnvType.CLIENT)` here:
https://github.com/TsukimiRen/Casualness-Delight/blob/e890bc65ec8398a2b32d7faa55432ea9b8679699/src/main/java/com/va11halla/casualness_delight/registry/BlocksRegistry.java#L48-L56

Solution:
```diff
--- @Environment(EnvType.CLIENT)
```

**Comment by JasdanVM** [comment]
> Caused by the `@Environment(EnvType.CLIENT)` here:
> 
> https://github.com/TsukimiRen/Casualness-Delight/blob/e890bc65ec8398a2b32d7faa55432ea9b8679699/src/main/java/com/va11halla/casualness_delight/registry/BlocksRegistry.java#L48-L56
> 
> Solution:
> 
> ```diff
> --- @Environment(EnvType.CLIENT)
> ```

Interesting, so, I'd have to change the mod's files to use it on the server?
I suppose I can wait for this to be included on an Update.

**Comment by KawaiShio** [comment]
Version 0.4c has been fixed

**Comment by KawaiShio** [comment]
> Caused by the `@Environment(EnvType.CLIENT)` here:
> 
> https://github.com/TsukimiRen/Casualness-Delight/blob/e890bc65ec8398a2b32d7faa55432ea9b8679699/src/main/java/com/va11halla/casualness_delight/registry/BlocksRegistry.java#L48-L56
> 
> Solution:
> 
> ```diff
> --- @Environment(EnvType.CLIENT)
> ```
Yes, it was a stupied mistake TAT
